apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fefd97j3p-go 
  janus-idp.io/tekton: fefd97j3p-go
  backstage.io/kubernetes-id: fefd97j3p-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fefd97j3p-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  